#include "stdafx.h"
#include "CppUnitTest.h"
#include "Mesh.h"
#include "SetOfElements.h"
#include "Elements/ElementHandler.h"
#include "Fields/Coordinates.h"
#include "FileIO/WriteVtk.h"
#include "TestClasses/DiffFiles.h"
#include "TestUtils/LogStream.h"
#include <fstream>
#include <iostream>
#include <memory>
