#include "stdafx.h"
#include "CppUnitTest.h"
#include "Mesh.h"
#include "FileIO/WriteAbaqusInp.h"
#include "TestClasses/DiffFiles.h"
#include "TestClasses/BoxMesh.h"
#include "TestUtils/LogStream.h"
#include <fstream>
#include <memory>
